### PR TITLE
Pyopencl blog update

### PR DESCRIPTION
**Pull request by albertgoncalves**
Thank you for the quick reply! (re: https://github.com/diku-dk/futhark-website/issues/9)
I tried to keep the changes purely restricted to the syntax, without stepping onto the style of the original, happy to adjust further if needs be.

I saved the image with `maptlotlib` as opposed to `PNG/pypng` -- but otherwise can attest that the updated code in this post works as advertised.

### CODE REVIEW

**Comment by athas** [comment]
Looks good, but if we're updating the code, we might as well make it more modern while we're there.  For example, this function:

```
  let dot (c: (f32,f32)): f32 =
    let (r, i) = c
    in r * r + i * i
    in r * r + i * i
```

This was written in the dark primordial times before Futhark supported tuple deconstruction in parameters.  Nowadays it can be written as:

```
  let dot (r: f32, i: f32): f32 =
    in r * r + i * i
    in r * r + i * i
```

Similarly for at least `multComplex` and `addComplex`.  Are you up for making this change as well?

There are also some text updates that should be made (the details in the blog post about entry points is outdated), but I think I should do that myself.

For extra points, could you also check that [mandelbrot.fut](https://futhark-lang.org/static/mandelbrot.fut) (the code linked in the blog post) actually corresponds to the blog post?  I think I may have partially updated it at one point so that it at least compiles, but your code is slightly different (*better*, because parameters like `screenX` are now on their own).

**Comment by albertgoncalves** [comment]
Additionally, I was never able to figure out this line, mentioned right above the first `.fut` code excerpt:
> For convenience, we ask that all decimal literals be considered single precision (the type ``f32`` in Futhark)::
```  
  default(f32)
```
Is this no longer a language feature? I wasn't able to find it mentioned in the documentation, though I could very well have just overlooked it (my apologies if so).

**Comment by athas** [comment]
`default` was removed some time ago.  It hails from a dark era before numeric literals were polymorphic.

**Comment by albertgoncalves** [comment]
Gotcha -- if that's the case this latest commit removes that line. Anything else I should tackle on this post? I think I addressed your previous comment w/ the few commits above.

**Comment by athas** [comment]
No, looks good to me.  Thanks!

**Comment by albertgoncalves** [comment]
Right on -- thanks for the help (and the merge)!

**Pull request merged**
